import Head from "next/head";

import Hero from "../components/home/Hero";
import Services from "../components/home/Services";

import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Next.js Bootstrap Starter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Hero />
        <Services />
      </main>
    </Layout>
  );
}
